PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>

DELETE {
  GRAPH ?g {
    ?s ?p ?o.
  }
}
INSERT {
  GRAPH ?g {
  ?newS ?p ?o.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <http://data.lblod.info/vocabularies/mobiliteit/Maatregelconceptcombinatie>;
           <http://mu.semte.ch/vocabularies/core/uuid> ?uuid.
    ?s ?p ?o.
  }

  BIND(IRI(CONCAT("http://data.lblod.info/maatregelconceptcombinaties/",?uuid)) AS ?newS)
}