PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>

DELETE {
  GRAPH ?g {
    ?s a ?type.
  }
}
INSERT {
  GRAPH ?g {
    ?s a <http://data.lblod.info/vocabularies/mobiliteit/Maatregelcombinatie>.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <http://data.lblod.info/vocabularies/mobiliteit/Verkeersbordcombinatie>.
    ?s a ?type.
  }
}