# Workaround sprintF issue....
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/1> a <http://data.vlaanderen.be/ns/besluit#Agendapunt>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/2> a <http://data.vlaanderen.be/ns/besluit#Artikel>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/3> a <http://data.vlaanderen.be/ns/besluit#BehandelingVanAgendapunt>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/4> a <http://data.vlaanderen.be/ns/besluit#Besluit>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/5> a <http://xmlns.com/foaf/0.1/Document>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/6> a <https://data.vlaanderen.be/ns/generiek#DocumentOnderdeel>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/7> a <http://data.europa.eu/eli/ontology#LegalExpression>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/8> a <http://data.europa.eu/eli/ontology#LegalResource>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/9> a <http://data.europa.eu/eli/ontology#LegalResourceSubdivision>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/10> a <http://data.vlaanderen.be/ns/besluit#Stemming>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/11> a <http://data.vlaanderen.be/ns/besluit#Vergaderactiviteit>.
    <http://dummy/ec2e93bb-1fb0-4e66-a930-f90e5ba33780/12> a <http://data.vlaanderen.be/ns/besluit#Zitting>.
  }
}



DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Agendapunt>.
    ?s ?p ?o.
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Artikel>.
    ?s ?p ?o.
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#BehandelingVanAgendapunt>.
    ?s ?p ?o.
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Besluit>.
    ?s ?p ?o.
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://xmlns.com/foaf/0.1/Document>.
    ?s ?p ?o.
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <https://data.vlaanderen.be/ns/generiek#DocumentOnderdeel>.
    ?s ?p ?o.
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.europa.eu/eli/ontology#LegalExpression>.
    ?s ?p ?o.
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.europa.eu/eli/ontology#LegalResource>.
    ?s ?p ?o.
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.europa.eu/eli/ontology#LegalResourceSubdivision>.
    ?s ?p ?o.
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Stemming>.
    ?s ?p ?o.
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Vergaderactiviteit>.
    ?s ?p ?o.
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Zitting>.
    ?s ?p ?o.
  }
}