(define-resource harvesting-task ()
  :class (s-prefix "ext:harvestingTask")
  :properties `((:status :string ,(s-prefix "adms:status"))
                (:created :dateTime ,(s-prefix "dct:created"))
                (:modified :dateTime ,(s-prefix "dct:modified"))
                (:creator :string ,(s-prefix "dct:creator"))
                (:type :uri-set ,(s-prefix "besluit:Agendapunt.type"))
                (:position :int ,(s-prefix "schema:position")))
  :has-one `((harvesting-collection :via ,(s-prefix "prov:generated")
                        :as "harvesting-collection"))
  :resource-base (s-url "http://data.lblod.info/id/harvesting-task/")
  :features '(include-uri)
  :on-path "harvesting-task")

(define-resource harvesting-collection ()
  :class (s-prefix "ext:harvestingTask")
  :properties `((:status :string ,(s-prefix "adms:status"))
                (:remote-data-object :dateTime ,(s-prefix "nfo:RemoteDataObject")))
  :has-many `((harvesting-task :via ,(s-prefix "ext:harvestingTask")
                        :as "harvesting-tasks"))
  :resource-base (s-url "http://data.lblod.info/id/harvesting-task/")
  :features '(include-uri)
  :on-path "harvesting-task")
