(define-resource harvesting-task ()
  :class (s-prefix "hrvst:HarvestingTask")
  :properties `((:status :string ,(s-prefix "adms:status"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:creator :string ,(s-prefix "dct:creator")))
  :has-one `((harvesting-collection :via ,(s-prefix "prov:generated")
                        :as "harvesting-collection"))
  :resource-base (s-url "http://data.lblod.info/id/harvesting-task/")
  :features '(include-uri)
  :on-path "harvesting-tasks")

(define-resource harvesting-collection ()
  :class (s-prefix "hrvst:harvestingCollection")
  :properties `((:status :string ,(s-prefix "adms:status"))
                (:remote-data-object :string ,(s-prefix "nfo:RemoteDataObject")))
  :has-many `((harvesting-task :via ,(s-prefix "hrvst:harvestingTask")
                        :as "harvesting-tasks"))
  :resource-base (s-url "http://data.lblod.info/id/harvesting-collection/")
  :features '(include-uri)
  :on-path "harvesting-collections")

(define-resource remote-data-object ()
  :class (s-prefix "nfo:RemoteDataObject")
  :properties `((:source :string ,(s-prefix "nie:url"))
                (:status :string ,(s-prefix "adms:status")))
  :resource-base (s-url "http://data.lblod.info/id/remote-data-object/")
  :features '(include-uri)
  :on-path "remote-data-objects")

