# Archive related mandatarissen - part 1
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/mandatarissen/60D062C1CA2C910008000037> ?p1 ?o1 .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    <http://data.lblod.info/id/mandatarissen/60D062C1CA2C910008000037> ?p1 ?o1 .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/mandatarissen/60D062C1CA2C910008000037> ?p1 ?o1 .
  }
}
;
# Archive related mandatarissen - part 2
DELETE {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    <http://data.lblod.info/id/mandatarissen/60D062C1CA2C910008000037> a ?type1 .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    <http://data.lblod.info/id/mandatarissen/60D062C1CA2C910008000037> a <http://lblod.data.gift/vocabularies/mandaat/ArchivedMandataris> ;
      <http://www.w3.org/2004/02/skos/core#historyNote> "Mandataris archived because linked to the wrong person" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    <http://data.lblod.info/id/mandatarissen/60D062C1CA2C910008000037> a ?type1 .
  }
}