PREFIX besluit:                           <http://lblod.data.gift/vocabularies/besluit/>
PREFIX lblodRule:                         <http://data.lblod.info/id/notification-rule/>
PREFIX BestuurseenheidClassificatieCode:  <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Delete Advies samenvoeging for Gemeente and Provincie
    lblodRule:61ab38bd-28bc-4ef1-9e06-ac900b60f216  besluit:decidableBy BestuurseenheidClassificatieCode:5ab0e9b8a3b2ca7c5e000001 , # Gemeente
                                                                        BestuurseenheidClassificatieCode:5ab0e9b8a3b2ca7c5e000000 . # Provincie

    # Delete Verslag lokale betrokkenheid for Gemeente and Provincie
    lblodRule:fa14e698-cc27-4d8e-944f-32209fca8adc  besluit:decidableBy BestuurseenheidClassificatieCode:5ab0e9b8a3b2ca7c5e000001 , # Gemeente
                                                                        BestuurseenheidClassificatieCode:5ab0e9b8a3b2ca7c5e000000 . # Provincie
  }
}
